// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTuVTdWRiLvfS7ZWY4vbQQX3QaAWUPREo',
    appId: '1:227449580108:web:8c9235b77ada4fdcee62e9',
    messagingSenderId: '227449580108',
    projectId: 'horus-bot-app',
    authDomain: 'horus-bot-app.firebaseapp.com',
    storageBucket: 'horus-bot-app.firebasestorage.app',
    measurementId: 'G-P7QDT0DK6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EHdyjVS3A6wPqNlqNgPIx1G9dRbCezQ',
    appId: '1:227449580108:android:d0549981bf45dcc9ee62e9',
    messagingSenderId: '227449580108',
    projectId: 'horus-bot-app',
    storageBucket: 'horus-bot-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmITd076jJqKDRVOrrKNbkfyejZFPnjU',
    appId: '1:227449580108:ios:26b27b79c4f43139ee62e9',
    messagingSenderId: '227449580108',
    projectId: 'horus-bot-app',
    storageBucket: 'horus-bot-app.firebasestorage.app',
    iosBundleId: 'com.example.museumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZmITd076jJqKDRVOrrKNbkfyejZFPnjU',
    appId: '1:227449580108:ios:26b27b79c4f43139ee62e9',
    messagingSenderId: '227449580108',
    projectId: 'horus-bot-app',
    storageBucket: 'horus-bot-app.firebasestorage.app',
    iosBundleId: 'com.example.museumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTuVTdWRiLvfS7ZWY4vbQQX3QaAWUPREo',
    appId: '1:227449580108:web:c841b0fc531baa15ee62e9',
    messagingSenderId: '227449580108',
    projectId: 'horus-bot-app',
    authDomain: 'horus-bot-app.firebaseapp.com',
    storageBucket: 'horus-bot-app.firebasestorage.app',
    measurementId: 'G-1PM1WBXFNV',
  );
}
